# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/configuration/#theme-parameters

autoSwitchAppearance          = false
colorScheme                   = "ocean"
defaultAppearance             = "dark"
defaultBackgroundImage        = ""
defaultFeaturedImage          = ""
disableImageOptimization      = false
disableImageZoom              = false
disableTextInHeader           = false
enableCodeCopy                = false
enableSearch                  = false
highlightCurrentMenuArea      = true
mainSections                  = [  ]
robots                        = ""
showLikes                     = ""
showViews                     = ""
smartTOC                      = ""
smartTOCHideUnfocusedChildren = ""

[header]
layout = "basic"

[footer]
showAppearanceSwitcher = false
showCopyright          = true
showMenu               = true
showScrollToTop        = true
showThemeAttribution   = false

[homepage]
cardView             = false
cardViewScreenWidth  = false
homepageImage        = ""
layout               = "profile"
layoutBackgroundBlur = false
showMoreLink         = false
showMoreLinkDest     = "/posts"
showRecent           = false
showRecentItems      = 6

[article]
editAppendPath              = true
editURL                     = ""
heroStyle                   = "basic"
invertPagination            = true
layoutBackgroundBlur        = true
layoutBackgroundHeaderSpace = true
relatedContentLimit         = 3
seriesOpened                = true
sharingLinks                = [  ]
showAuthor                  = true
showAuthorBottom            = false
showAuthorsBadges           = true
showBreadcrumbs             = true
showComments                = false
showDate                    = true
showDateOnlyInArticle       = false
showDateUpdated             = true
showDraftLabel              = true
showEdit                    = false
showHeadingAnchors          = true
showHero                    = true
showLikes                   = false
showPagination              = true
showReadingTime             = true
showRelatedContent          = false
showSummary                 = true
showTableOfContents         = true
showTaxonomies              = true
showViews                   = false
showWordCount               = true
showZenMode                 = false

[list]
cardView                    = true
cardViewScreenWidth         = true
constrainItemsWidth         = true
groupByYear                 = true
heroStyle                   = "background"
layoutBackgroundBlur        = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs             = true
showCards                   = true
showHero                    = true
showLikes                   = false
showSummary                 = true
showTableOfContents         = true
showViews                   = false

[sitemap]
excludedKinds = [  ]

[taxonomy]
cardView            = false
heroStyle           = "background"
showBreadcrumbs     = false
showHero            = false
showLikes           = false
showTableOfContents = false
showTermCount       = true
showViews           = false

[firebase]
apiKey            = ""
appId             = ""
authDomain        = ""
measurementId     = ""
messagingSenderId = ""
projectId         = ""
storageBucket     = ""

[fathomAnalytics]
domain = ""
site   = ""

[umamiAnalytics]
domain    = ""
websiteid = ""

[BuyMeACoffee]
globalWidget         = ""
globalWidgetColor    = ""
globalWidgetMessage  = ""
globalWidgetPosition = ""
identifier           = ""

[verification]
bing      = ""
google    = ""
pinterest = ""
yandex    = ""
